source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'FootFight' do
    pod 'Alamofire'
    pod 'MagicalRecord'
    pod 'ICSPullToRefresh'
    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxBlocking'
    pod 'RxTests'
end
